server:
  port: 8081
  servlet:
    context-path: /user

spring:
  application:
    name: user-service
  datasource:
    url: "jdbc:postgresql://localhost:5434/user_db"
    driver-class-name: "org.postgresql.Driver"
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/HBvibe_Web
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
idp:
  url: http://localhost:8080
  client-id: HBvibe_web_backend
  client-secret: Fsr9ii9HLX70nWmj9fus2N4IT5VEZQmB

